---
#-------------------------------
# General Site Settings
title: free git hosting
logo: # You can add own logo. For example '/images/logo.png'.
description: Everything you need to know about free git hosting. Find Articles related to the best free git hosting services, including GitHub, GitLab, Bitbucket, and more. Compare features, pricing, and user reviews to find the perfect solution for your needs.
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://free-git-hosting.github.io" # The base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Author Settings
author:
  avatar: "/images/Author-codingRhodes.webp"
  name: Coding Rhodes
  job: Passionate Developer & Content Writer. 
  description: 'CodingRhodes is a passionate developer and tech enthusiast who loves to explore the world of programming and technology. With a keen interest in web development, software engineering, and open-source projects, CodingRhodes shares valuable insights, tutorials, and resources to help fellow developers enhance their skills and stay updated with the latest trends in the tech industry.'

social:
  # - {icon: "ion-logo-twitter", link: "https://twitter.com"}
  - {
      icon: "ion-logo-youtube",
      link: "https://www.youtube.com/channel/UCKaEeeAcNbyTttL-MrHitvw",
    }
  - {
      icon: "ion-arrow-dropright-circle",
      link: "https://space.bilibili.com/673434640",
    }
# - {icon: "ion-logo-instagram", link: "https://instagram.com"}
# - {icon: "ion ion-logo-github", link: "https://github.com"}
#

# Example of adding a new link to the author section and footer - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Featured Slider
slider: true # NOTE - By default, the slider is set to display featured posts. To add featured post to the slider, add the field, featured: true in the YAML front matter block. If you do not want to use the slider, leave the slider field empty.

#-------------------------------
# Contact Settings
contact:
  email: zitao.jerry.liu@gmail.com # Add your email for contant form
  description: Bonso comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Bonso comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: dr-ai4ed # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Google Analytics
google-analytics: UA-166862523-1
# Add your identifier. For example UA-99631805-1.

#-------------------------------
# Newsletter
mailchimp: false # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-text: Subscribe to our newsletter and we’ll send you the emails of latest posts. # Add your description.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

#-------------------------------
# Build settings
markdown: kramdown
permalink: /:categories/:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: /:title

sass:
  sass_dir: _sass
  style: compressed

future: true