# Site
name: Git Hosting
title: free git hosting
logo: '/assets/images/favicon.ico'
description: Everything you need to know about free git hosting. Find Articles related to the best free git hosting services, including GitHub, GitLab, Bitbucket, and more. Compare features, pricing, and user reviews to find the perfect solution for your needs.
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://free-git-hosting.github.io" # The base hostname & protocol for your site, e.g. http://example.com

baseurl: ''
disqus: 'codingrhodes'
email: 'codingrhodes@gmail.com'
mailchimp-list: 'https://github.us22.list-manage.com/subscribe/post?u=7cbb8f4ffba4384950451d221&amp;id=aae56f1824&amp;f_id=00c8c2e1f0'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
author:
  avatar: "/assets/images/Author-codingRhodes.webp"
  name: Coding Rhodes
  job: Passionate Developer & Content Writer. 
  description: 'CodingRhodes is a passionate developer and tech enthusiast who loves to explore the world of programming and technology. With a keen interest in web development, software engineering, and open-source projects, CodingRhodes shares valuable insights, tutorials, and resources to help fellow developers enhance their skills and stay updated with the latest trends in the tech industry.'

social:
  # - {icon: "ion-logo-twitter", link: "https://twitter.com"}
  - {
      icon: "ion-logo-twitter",
      link: "https://x.com/CodingRhodes",
    }

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/Author-codingRhodes.webp
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]